### ISSUE TITLE
Question about potential refactor for get_reward in AIController2D/3D

### ISSUE THREAD

**Issue by Ivan-267** [edbeeching/godot_rl_agents_plugin#17]
Currently, the get_reward method is set to need to be implemented in the extended AIController2D/3D:

https://github.com/edbeeching/godot_rl_agents_plugin/blob/5b09dc906eae1e037c4f8b0b09a1ffe11340802f/addons/godot_rl_agents/controller/ai_controller_3d.gd#L25-L27

And for example in the custom environment [tutorial](https://github.com/edbeeching/godot_rl_agents/blob/a5ea2a36b3a0b665dc745be54f80cc9f38e659b0/docs/CUSTOM_ENV.md?plain=1#L119) it is implemented as:
```gdscript 
func get_reward() -> float:	
	return reward
```

Which seems to be returning the reward that is in the base class.

Is this needed to allow some kind of reward shaping before the reward is sent to the RL algorithm, or could we refactor the base class implementation to return reward and remove the requirement to override it in the inherited class? 

- If the reward will usually be updated in the agent/player class, then the refactor would reduce the amount of methods that need to be overriden, and custom functionality would still be possible when needed (method can still be overridden if needed). 
- If the reward will usually be calculated in the extended AIController, based e.g. on signals received from the agent/player class, then overriding the method will be frequent.

The main question is should overriding the method be a requirement, or should it have a default implementation which still leaves the option of possible extension when needed.

**Comment by edbeeching** [comment]
Hey, good point. I agree.

**Comment by Ivan-267** [comment]
As one potential solution is in the PR we can consider for the future (it would require env changes), I will close this issue for now.
