### ISSUE TITLE
Discrete action space returns only two values despite setting larger size

### ISSUE THREAD

**Issue by aethrvmn** [edbeeching/godot_rl_agents_plugin#41]
I have set up a custom env with a discrete action space using AIController2D, with 5 discrete actions:

```gdscript
func get_action_space() -> Dictionary:
    return {
        "move" : {
            "size": 5,
            "action_type": "discrete"
        }
    }
```

however every time the results are always 0s and 1s.

As far as I can tell this part of `sync.gd` is responsible:

```gdscript
func _extract_action_dict(action_array: Array, action_space: Dictionary):
    var index = 0
    var result = {}
    for key in action_space.keys():
        var size = action_space[key]["size"]
        if action_space[key]["action_type"] == "discrete":
            result[key] = round(action_array[index])
            print(result[key])
        else:
            result[key] = action_array.slice(index, index + size)
        index += size

    return result
```

since it is the only reference to discrete actions in the file.

I noticed that the function is only called in `_inference_process()`, don't know if that is relative or not.

The weird thing is that if I change the `size` to `1` I get only one value, as expected, so it does parse the `size`, and also changing `action_type` to `continuous` does result in an array of 5 elements.

**Comment by Ivan-267** [comment]
Hello,

Thanks for reporting the issue. There is a known issue with discrete actions not being supported with SB3 in the previous versions. I have just merged an update today to the [Godot RL Agents branch](https://github.com/edbeeching/godot_rl_agents) and the plugin repository here that adds support for discrete actions larger than 2.

The support is as follows:
- You can use all continuous actions, or all discrete actions with SB3, mixing them is still not supported properly as SB3 doesn't support that (it's supported with Rllib).

Try installing the Godot RL Agents from the Github repository linked above as well as using the updated Godot plugin from this repository.

**Comment by aethrvmn** [comment]
Thanks for the response!

I saw the merge some hours ago and I tried to implement Rllib but I run into some issues with .NET (my fault) since it needs to be compiled using the mono version and my distro doesn't package it.

I didn't notice that the update also works for SB3 and after trying it it appears to work!
